alias logs='cd /var/log/pinkbox/delivery'
alias mgr='cd $HOME/delivery/apps/pinkbox/management; RAILS_ENV=delivery ./bin/console'
alias root='cd $HOME/delivery/apps/pinkbox'
alias ps='/usr/ucb/ps'

# PINKBOX
alias pb_start='export RAILS_ENV="delivery"; cd $HOME/$RAILS_ENV/apps/pinkbox/management; rake startup && ./bin/run ./etc/deployment_scripts/$RAILS_ENV/start_pinkbox_as_threads.ds'
alias pb_starti='export RAILS_ENV="integration"; cd $HOME/$RAILS_ENV/apps/pinkbox/management; rake startup && ./bin/run ./etc/deployment_scripts/$RAILS_ENV/start_pinkbox_as_threads.ds'
alias pb_stop='export RAILS_ENV="delivery"; cd $HOME/$RAILS_ENV/apps/pinkbox/management; ./bin/run ./etc/deployment_scripts/$RAILS_ENV/stop_pinkbox.ds && rake shutdown shutdown_management_mq'
alias pb_stopi='export RAILS_ENV="integration"; cd $HOME/$RAILS_ENV/apps/pinkbox/management; ./bin/run ./etc/deployment_scripts/$RAILS_ENV/stop_pinkbox.ds && rake shutdown shutdown_management_mq'
alias pb_console='export RAILS_ENV="delivery"; cd $HOME/$RAILS_ENV/apps/pinkbox/management; ./bin/console'
alias pb_consolei='export RAILS_ENV="integration"; cd $HOME/$RAILS_ENV/apps/pinkbox/management; ./bin/console'
alias pb_delivery='export RAILS_ENV="delivery"; cd $HOME/$RAILS_ENV/apps/pinkbox/management'
alias pb_integration='export RAILS_ENV="integration"; cd $HOME/$RAILS_ENV/apps/pinkbox/management'
alias pb_logs='cd /var/log/pinkbox/delivery && ls -latF'
alias pb_logsi='cd /var/log/pinkbox/integration && ls -latF'
alias pb_t='tail -f /var/log/pinkbox/$RAILS_ENV/rapid_decision/core_rindlets_* /var/log/pinkbox/$RAILS_ENV/underwriting_system/underwriting_rindlets_*'
alias pb_tail='tail -1111f /var/log/pinkbox/$RAILS_ENV/rapid_decision/core_rindlets_* /var/log/pinkbox/$RAILS_ENV/underwriting_system/underwriting_rindlets_* /var/log/pinkbox/$RAILS_ENV/rinda_server/rinda_delivery.log'
