# Delete this file if you don't use TextMate
# Textmate Editing and Sourcing aliases
export EDITOR="$HOME/bin/mate"
alias e="$EDITOR ."
alias ea="$EDITOR $DOT_ENV_PATH/host/$HOSTNAME/alias.sh"
alias eas=". $DOT_ENV_PATH/host/$HOSTNAME/alias.sh"
alias eb="$EDITOR $HOME/bin"
alias ee="$EDITOR $DOT_ENV_PATH $HOME/.bashrc"
alias ees=". $DOT_ENV_PATH/source.sh"
alias ef="$EDITOR $DOT_ENV_PATH/host/$HOSTNAME/functions.sh"
alias efs=". $DOT_ENV_PATH/host/$HOSTNAME/functions.sh"
alias eh="$EDITOR $HOME/.ssh"
alias ep="$EDITOR $DOT_ENV_PATH/host/$HOSTNAME/path.sh"
alias eps=". $DOT_ENV_PATH/host/$HOSTNAME/path.sh"
alias m="$EDITOR"
alias vi="$EDITOR"
