# Delete this file if you don't use TextMate
# Textmate Editing and Sourcing aliases
# export EDITOR="$HOME/bin/mate -a"
# export EDITOR="$HOME/bin/mate2 -w"
export EDITOR="$HOME/bin/subl"
alias e="$EDITOR ."
alias ea="$EDITOR $dot_env_path/host/$HOSTNAME/alias.sh"
alias eas=". $dot_env_path/host/$HOSTNAME/alias.sh"
alias eb="$EDITOR $HOME/bin"
alias ee="$EDITOR $dot_env_path $HOME/.bashrc"
alias ees=". $dot_env_path/source.sh"
alias ef="$EDITOR $dot_env_path/host/$HOSTNAME/functions.sh"
alias efs=". $dot_env_path/host/$HOSTNAME/functions.sh"
alias eh="$EDITOR $HOME/.ssh"
alias ep="$EDITOR $dot_env_path/host/$HOSTNAME/path.sh"
alias eps=". $dot_env_path/host/$HOSTNAME/path.sh"
alias m="$EDITOR"
alias vi="$EDITOR"
